var appConstants = {
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  UPDATE_ITEM: "UDPDATE_ITEM",
  TOGGLE_ITEM: "TOGGLE_ITEM",
  COMPLETE_OR_CANCEL_ALL_ITEMS: "COMPLETE_OR_CANCEL_ALL_ITEMS",
  UPDATE_SHOW_ITEM_STRATEGY: "UPDATE_SHOW_ITEM_STRATEGY"
};

module.exports = appConstants;